### PR TITLE
Add Rubocop to CI

### PR DESCRIPTION
**Pull request by nschonni**
Autogenerated the config that ignores all the current rules that are failing, and add CI job to run when the ruby files are changed

### CODE REVIEW

**Comment by ohler55** [comment]
Is this just a helper to reduce the time in actions when something fails?

**Comment by nschonni** [comment]
Similar to the `clang-format` except it's the linter for the Ruby files https://rubocop.org/

**Comment by ohler55** [comment]
hmm, not sure I'm on board with the rules. 10 years ago when Ox was written the convention for method names was to use underscores and not camel case for method names. I don't see the value in making changes just to follow the latest conventions as it will break existing user code.

**Comment by nschonni** [comment]
The rules you don't like can be left off, but a bunch have options to say stuff like "I preffer snake case" so it would complain if someone now added camelCase

**Comment by ohler55** [comment]
Are you willing to take a first cut at rules that match the code and we can look at the exceptions together?

**Comment by ohler55** [comment]
I'm a bit surprised the files were that consistent. Nice.

**Comment by nschonni** [comment]
The stuff in `.rubocop-todo.yml` are the bits that don't conform right now, but I'll see about sending some PRs to fix stuff, then you can decide to accept or ignore the rules

**Comment by ohler55** [comment]
That's a pretty long file.

**Comment by nschonni** [comment]
Yeah, some my just get ignored if you don't like them by setting them as `Enabled: false` in the root `.rubocop.yml`

**Pull request merged**
