### PR TITLE
Run clang format in CI

### PR DESCRIPTION
**Pull request by nschonni**
Noticed the config, so thought having it in the CI would make sense

### CODE REVIEW

**Comment by ohler55** [comment]
There is a .clang-format file at the root of the Ox repo. Please use that when running clang-format. I'm not sure if all the files are perfect but I clang-format on sax_buf.c and got only one difference not the same as what the proposed script got. I used v15.0.7 which is the latest for a brew install even though the latest is v17.0.0. Still I would not expect that big a change.

**Comment by ohler55** [comment]
BTW, I would like to see this as part of CI so thank you for getting it started.

**Comment by nschonni** [comment]
I think this action defaults to `13` currently, so I'll see what the change is explicitly setting it to `15`

**Comment by ohler55** [comment]
I don't think the version is the issue. I think the .clang-format is not being used. I'm looking into it now as well.

**Comment by ohler55** [comment]
I've been using clang-format from inside emacs but from the looks of it only some subset of the rules are being used. I'll format the files according to the .clang-format style and then see if this PR come out with a clean CI.

**Comment by ohler55** [comment]
Pushed the reformatted files. I had to make some other changes since clang-format wants all includes sorted by name. Please base this PR on the reformatted files.

**Comment by nschonni** [comment]
Looks like that got the bulk of it, but there are still a few additional ones it's still complaining about

**Comment by ohler55** [comment]
Adding the required ruby.h header broke the formatting. That and the test C files were not formatted. Please try again.

**Comment by nschonni** [comment]
Looks like it's happy now

**Comment by ohler55** [comment]
Yes it does. Thank you for you patience.

**Pull request merged**
