### PR TITLE
Whitespace text

### PR DESCRIPTION
**Pull request by raphaeleidus**

### CODE REVIEW

**Comment by ohler55** [comment]
I can not accept this PR as it is. It changes the behavior of the existing :skip option which would break many other peoples code.

I think what you are looking for, correct me if I am wrong, is an addition :skip option in addition to the 3 existing values.

**Comment by raphaeleidus** [comment]
noted, thank you. I will rework

**Comment by ohler55** [comment]
👍

**Comment by ohler55** [comment]
Are you planning on reworking or dropping this?

**Comment by ohler55** [comment]
I guess it is a drop since no response,

**Pull request closed without merging**
